/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * <h2><center>&copy; Copyright (c) 2024 STMicroelectronics.
 * All rights reserved.</center></h2>
 *
 * This software component is licensed by ST under BSD 3-Clause license,
 * the "License"; You may not use this file except in compliance with the
 * License. You may obtain a copy of the License at:
 *                        opensource.org/licenses/BSD-3-Clause
 *
 ******************************************************************************
 */
#include <stdio.h>
#include <stdint.h>
typedef volatile unsigned int vuint32_t;
#define RCC_BASE 0x40021000
#define PORTA_BASE 0x40010800
#define RCC_APB2ENR *(volatile uint32_t *) (RCC_BASE + 0x18)
#define GPIO_PA_CRH *(volatile uint32_t *) (PORTA_BASE + 0x04)
#define GPIO_PA_ODR *(volatile uint32_t *) (PORTA_BASE + 0x0C)


extern void NMI_Handler(void)
{

}

extern void Bus_Fault_Handler(void)
{

}	

typedef union {
	vuint32_t allfeilds;
	struct{
		vuint32_t pin0:1;
		vuint32_t pin1:1;
		vuint32_t pin2:1;
		vuint32_t pin3:1;
		vuint32_t pin4:1;
		vuint32_t pin5:1;
		vuint32_t pin6:1;
		vuint32_t pin7:1;
		vuint32_t pin8:1;
		vuint32_t pin9:1;
		vuint32_t pin10:1;
		vuint32_t pin11:1;
		vuint32_t pin12:1;
		vuint32_t pin13:1;
		vuint32_t pin14:1;
		vuint32_t pin15:1;
		vuint32_t pin16:1;
		vuint32_t pin17:1;
		vuint32_t pin18:1;
		vuint32_t pin19:1;
		vuint32_t pin20:1;
		vuint32_t pin21:1;
		vuint32_t pin22:1;
		vuint32_t pin23:1;
		vuint32_t pin24:1;
		vuint32_t pin25:1;
		vuint32_t pin26:1;
		vuint32_t pin27:1;
		vuint32_t pin28:1;
		vuint32_t pin29:1;
		vuint32_t pin30:1;
		vuint32_t pin31:1;

	}pins;
}R_ODR_t;

volatile R_ODR_t* R_ODR = (volatile R_ODR_t*)(PORTA_BASE + 0x0C);
unsigned char Variables[]={1,2,3};
unsigned char const constvariables[]={1,2,3};
unsigned char uninit[3];

int main(void)
{
	RCC_APB2ENR |= 1<<2;
	GPIO_PA_CRH &= 0xFF0FFFFF;
	GPIO_PA_CRH |= 0x00200000;
	while(1)
	{
		R_ODR->pins.pin13=1;
		for(int i=0;i<5000;i++);
		R_ODR->pins.pin13=0;
		for(int i=0;i<5000;i++);
	}
	return 0;
}
